name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Compile
      run: javac -d target/classes Testing/src/main/java/*.java

    - name: Test Addition
      run: |
        result=$(java -cp target/classes Main add 5 3)
        echo "Result: $result"
        if [ "$result" -eq 8 ]; then
          echo "Addition test passed"
        else
          echo "Addition test failed"
          exit 1
        fi

    - name: Test Division
      run: |
        result=$(java -cp target/classes Main divide 10 2)
        echo "Result: $result"
        if [ "$result" -eq 5 ]; then
          echo "Division test passed"
        else
          echo "Division test failed"
          exit 1
        fi

    - name: Test Division by Zero
      run: |
        set +e
        result=$(java -cp target/classes Main divide 5 0)
        echo "Result: $result"
        set -e
        if echo "$result" | grep -q "Exception"; then
          echo "Division by zero test passed"
        else
          echo "Division by zero test failed"
          exit 1
        fi
